-- File: sipo.vhd
-- Generated by MyHDL 0.11
-- Date: Tue Jan  4 17:07:34 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity clockdevider is
    port (
		clk_in: 		in std_logic;
		clk_out:		out std_logic := '0'
    );
end entity clockdevider;

architecture devider of clockdevider is
	signal counter: integer := 0; 
	signal clk: std_logic := '0';
begin
	process (clk_in) is
	begin
		if rising_edge(clk_in) then
			if counter > 11 then 
				counter <= 0;
				clk <= not clk; 
			else
				counter <= counter + 1; 
			end if;
		end if; 
	end process;
	clk_out <= clk;
end architecture devider;
