-- File: sipo.vhd
-- Generated by MyHDL 0.11
-- Date: Tue Jan  4 17:07:34 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sipo is
    port (
        clk: 		in std_logic;
        clr: 		in std_logic;
		  sipo_en: 	in std_logic;
        din: 		in std_logic;
        dout: 		out std_logic_vector(47 downto 0)
    );
end entity sipo;

architecture MyHDL of sipo is
signal sig: std_logic_vector(47 downto 0);
begin

process(sig) is 
begin
	dout <= sig;
end process; 

process (clk) is
begin
    if rising_edge(clk) then
        if (clr = '1') then
            sig <= (others=> '0') after 5 ns;
        elsif sipo_en = '1' then
            sig <= sig(46 downto 0) & din after 5 ns;
        end if;
		  --dout <= sig; 
    end if;
end process;


end architecture MyHDL;
