-- File: vhdl_out/audio_rectifier.vhd
-- Generated by MyHDL 0.11
-- Date: Wed Jan 26 15:13:50 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity audio_rectifier is
    port (
        clk: in std_logic;
        en: in std_logic;
        audio_in: in std_logic_vector(23 downto 0);
        audio_out: out std_logic_vector(9 downto 0)
    );
end entity audio_rectifier;


architecture MyHDL of audio_rectifier is



signal audio_in_num: signed (23 downto 0);
signal audio_out_num: unsigned(9 downto 0);

begin

audio_in_num <= signed (audio_in);
audio_out <= std_logic_vector(audio_out_num);



AUDIO_RECTIFIER_LOGIC: process (clk) is
begin
    if rising_edge(clk) then
        if (en = '1') then
            if (audio_in_num >= 0) then
                audio_out_num <= resize(unsigned(shift_right(audio_in_num, 14)), 10);
            else
                audio_out_num <= to_unsigned(0, 10);
            end if;
        end if;
    end if;
end process AUDIO_RECTIFIER_LOGIC;

end architecture MyHDL;
