-- File: vhdl_out/blk_clock_divider.vhd
-- Generated by MyHDL 0.11
-- Date: Wed Jan 26 15:32:26 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity blk_clock_divider is
    port (
        clk: in std_logic;
        en: in std_logic;
        clk_out: out std_logic
    );
end entity blk_clock_divider;


architecture MyHDL of blk_clock_divider is



signal clk_out_sig: std_logic;
signal counter: unsigned(7 downto 0);

begin





clk_out <= clk_out_sig;

BLK_CLOCK_DIVIDER_UPDATE_OUTPUT: process (clk) is
begin
    if falling_edge(clk) then
        if (counter = 128) then
            if (en = '1') then
                clk_out_sig <= stdl((not bool(clk_out_sig)));
            else
                clk_out_sig <= '0';
            end if;
        end if;
    end if;
end process BLK_CLOCK_DIVIDER_UPDATE_OUTPUT;

BLK_CLOCK_DIVIDER_CNT_UPDATE: process (clk) is
begin
    if falling_edge(clk) then
        if (en = '1') then
            if (counter < 128) then
                counter <= (counter + 1);
            else
                counter <= to_unsigned(0, 8);
            end if;
        else
            counter <= to_unsigned(0, 8);
        end if;
    end if;
end process BLK_CLOCK_DIVIDER_CNT_UPDATE;

end architecture MyHDL;
