-- File: ../vhdl/video_controller/drawn_memory.vhd
-- Generated by MyHDL 0.11
-- Date: Tue Jan  4 17:30:43 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity drawn_memory is
    port (
        clk: in std_logic;
        inputs_clr: in std_logic;
        inputs_sq_t: in std_logic;
        inputs_tri_t: in std_logic;
        inputs_sin_t: in std_logic;
        outputs_sq_o: out std_logic;
        outputs_sin_o: out std_logic;
        outputs_tri_o: out std_logic
    );
end entity drawn_memory;


architecture MyHDL of drawn_memory is



signal sin_reg: std_logic;
signal sq_reg: std_logic;
signal tri_reg: std_logic;

begin





outputs_sin_o <= sin_reg;
outputs_sq_o <= sq_reg;
outputs_tri_o <= tri_reg;

DRAWN_MEMORY_UPDATE_REGS: process (clk) is
begin
    if rising_edge(clk) then
        if (inputs_clr = '1') then
            sq_reg <= '0';
            tri_reg <= '0';
            sin_reg <= '0';
        else
            if (inputs_sq_t = '1') then
                sq_reg <= stdl((not bool(sq_reg)));
            end if;
            if (inputs_tri_t = '1') then
                tri_reg <= stdl((not bool(tri_reg)));
            end if;
            if (inputs_sin_t = '1') then
                sin_reg <= stdl((not bool(sin_reg)));
            end if;
        end if;
    end if;
end process DRAWN_MEMORY_UPDATE_REGS;

end architecture MyHDL;
