-- File: ../vhdl/video_controller\gen_offset.vhd
-- Generated by MyHDL 0.11
-- Date: Tue Jan  4 20:49:21 2022


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity gen_offset is
    port (
        sin_in: in std_logic_vector(5 downto 0);
        tri_in: in std_logic_vector(5 downto 0);
        sq_in: in std_logic_vector(5 downto 0);
        sin_o: out std_logic_vector(5 downto 0);
        tri_o: out std_logic_vector(5 downto 0);
        sq_o: out std_logic_vector(5 downto 0)
    );
end entity gen_offset;


architecture MyHDL of gen_offset is



signal sin_in_num: unsigned(5 downto 0);
signal sin_o_num: unsigned(5 downto 0);
signal sq_in_num: unsigned(5 downto 0);
signal sq_o_num: unsigned(5 downto 0);
signal tri_in_num: unsigned(5 downto 0);
signal tri_o_num: unsigned(5 downto 0);

begin

sin_in_num <= unsigned(sin_in);
tri_in_num <= unsigned(tri_in);
sq_in_num <= unsigned(sq_in);
sin_o <= std_logic_vector(sin_o_num);
tri_o <= std_logic_vector(tri_o_num);
sq_o <= std_logic_vector(sq_o_num);




sin_o_num <= resize(unsigned(((60 - 1) - signed(resize(sin_in_num, 7))) - 20), 6);
tri_o_num <= resize(unsigned(((60 - 1) - signed(resize(tri_in_num, 7))) - 20), 6);
sq_o_num <= resize(unsigned(((60 - 1) - signed(resize(sq_in_num, 7))) - 20), 6);

end architecture MyHDL;
